# Generated by Django 4.0.1 on 2022-02-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
