# Generated by Django 4.0.1 on 2022-02-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.CharField(max_length=20)),
                ('total', models.IntegerField()),
                ('shipping', models.IntegerField(default=0)),
                ('finalAmount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Not Packed'), (2, 'packed'), (3, 'Out For Delivery'), (4, 'Deliverd')], default=1)),
                ('paymentStatus', models.IntegerField(choices=[(1, 'Pending'), (2, 'Success')], default=1)),
                ('mode', models.IntegerField(choices=[(1, 'COD'), (2, 'Net Banking')], default=1)),
                ('time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=None)),
                ('orderId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('paymentId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('paymentSignature', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
    ]
