# Generated by Django 4.0.1 on 2022-02-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
